name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # PR情報チェック
  pr-info:
    name: PR情報チェック
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PR title check
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .+'
          allowed_prefixes: 'feat,fix,docs,style,refactor,test,chore'
          prefix_case_sensitive: false

      - name: Check PR size
        uses: pascalgn/size-label-action@v0.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sizes: >
            {
              "0": "XS",
              "20": "S", 
              "50": "M",
              "200": "L",
              "800": "XL"
            }

  # 変更ファイル分析
  changes:
    name: 変更ファイル分析
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.src }}
      tests: ${{ steps.changes.outputs.tests }}
      docs: ${{ steps.changes.outputs.docs }}
      config: ${{ steps.changes.outputs.config }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'src/**'
            tests:
              - 'src/**/__tests__/**'
              - '**/*.test.*'
              - '**/*.spec.*'
            docs:
              - 'docs/**'
              - '*.md'
            config:
              - 'package.json'
              - 'tsconfig.json'
              - 'next.config.*'
              - '.eslintrc.*'
              - 'tailwind.config.*'

  # 条件付きテスト実行
  conditional-tests:
    name: 条件付きテスト実行
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.src == 'true' || needs.changes.outputs.tests == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run affected tests
        run: npm run test -- --coverage --watchAll=false --changedSince=origin/main
        env:
          CI: true

  # ドキュメント検証
  docs-check:
    name: ドキュメント検証
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.docs == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.github/mlc_config.json'

      - name: Validate markdown format
        run: |
          # markdownlintの設定があれば実行
          if [ -f ".markdownlint.json" ]; then
            npx markdownlint "**/*.md"
          fi